# roles/mysql_database/meta/main.yml
---
galaxy_info:
  author: YourName
  description: Role to install and configure MySQL server.
  company: YourCompany
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy

  categories:
    - database

dependencies: []

