---
- name: Install a specific package on all managed nodes
  hosts: web
  become: yes
  tasks:
    - name: Ensure the package is installed
      ansible.builtin.apt:
        name: apache2
        state: present
