---
# tasks file for mysql_database
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
  become: true

- name: Start and enable MySQL service
  service:
    name: mysql
    state: started
    enabled: true
  become: true

- name: Set MySQL root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  with_items:
    - localhost
    - 127.0.0.1
    - ::1
  when: mysql_root_password != ''
  become: true

- name: Remove anonymous MySQL users
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  become: true

- name: Remove the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  become: true

- name: Create MySQL database
  mysql_db:
    name: "{{ mysql_databases }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  become: true

- name: Create MySQL user
  mysql_user:
    name: "{{ mysql_users.name }}"
    password: "{{ mysql_users.password }}"
    priv: "{{ mysql_users.priv }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  become: true

